-
  name: 'Postgres cluster database operation for DBA by Giovanni Barbato'
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: yes
  vars:
  vars_files:
    - ./roles/postgresTask4DBA/vars/new_database_var.yml
    #- ./roles/postgresTask4DBA/vars/cluster_params.yml
    - ./roles/postgresTask4DBA/vars/set_parameters_var.yml
  roles:
    - postgresTask4DBA
